name: Checke unifreq K5.4

env:
  REPO_URL: https://github.com/unifreq/linux-5.4.y
  REPO_BRANCH: main

on:
  schedule:
    - cron: 0 18 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Get Commit Hash
      id: getHash
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH .
        echo "::set-output name=commitHash::$(git rev-parse HEAD)"

    - name: Compare Commit Hash
      id: cachehash
      uses: actions/cache@v2
      with:
        path: .commitHash
        key: HEAD-${{ steps.getHash.outputs.commitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.gethash.outputs.commitHash }} | tee .commitHash

    - name: Trigger build
      if: steps.cachehash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        event-type: Compile-auto
        client-payload: '{"kernel_version": "5.4.100"}'

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
